### ISSUE TITLE
get duncan access to parse

### ISSUE THREAD

**Issue by duncangraham** [freindst/Argo-Project-V0#25]
what do I need to do to get access to parse @freindst?

**Comment by freindst** [comment]
I think it would be a good idea to let you see the tables in Parse, though there is no need to modify it.
username: battlehackchicago2015@awesomefat.com
password: Drag0nflaps

**Comment by duncangraham** [comment]
@freindst probably not the best move to post login deets on a public github repo. deleting this thread
