### ISSUE TITLE
move off Parse

### ISSUE THREAD

**Issue by duncangraham** [freindst/Argo-Project-V0#31]
Parse isn't an ideal solution and has been more of a pain than a benefit.

as per chat, @freindst and I agreed to move off of it onto our own database. 

I'll post updates in this thread and I'll be working on the db branch

**Comment by duncangraham** [comment]
Going to move forward with mysql. postgres is awesome, but is overkill at this point and would take more effort to get up and running.

**Comment by duncangraham** [comment]
the mysql setup is up and running! if you pull the latest from the db branch you can test it locally (or look at the gif below)

*next steps*
- [ ] duncan clean's up some code
- [ ] merge db branch with master
- [ ] add passport (http://passportjs.org/) for user accounts
- [ ] build bus model
- [ ] add functionality (currently commented out in app.js) back in

I'll likely make some tickets for the points above to further track things. The db branch gives us a much better base to continue work though. Once its merged I can walk you through how to get your environment set up if you hit any bumps @freindst 

![db](https://cloud.githubusercontent.com/assets/865298/8769757/57d7edba-2e72-11e5-850c-3f07ad5b7705.gif)

**Comment by freindst** [comment]
Looks great!

**Comment by duncangraham** [comment]
merged with master, adding passport now

**Comment by duncangraham** [comment]
passport's added. now to go through the dev process of getting that all squared away with the DB. once that's done we can move forward with adding a bus model.

**Comment by duncangraham** [comment]
I think this ticket has served its purpose. It's too broad at this point to be useful. closing in favor of more actionable (and smaller scope) tickets
