### ISSUE TITLE
accounts work

### ISSUE THREAD

**Issue by duncangraham** [freindst/Argo-Project-V0#34]
using this ticket to track the progress of adding user accounts. (sub task of #31)

This is my current understanding of the User model
- first name
- last name
- email
- password
- address
- createdAt (date user was made)
- CC stuff ( @freindst I'm assuming that we store a token or something from braintree? )
- buses (should be able to sort these by attended vs created)

## progress tracker
- [x] sign up
- [x] move passport-local-sequlize outside of node_modules (since its customized) 
- [x] login

**Comment by freindst** [comment]
I am meeting this problem: Unhandled rejection SequelizeConnectionError: ER_BAD_DB_ERROR: Unknown database 'argo_dev'.
@duncangraham, do you have any idea?

**Comment by duncangraham** [comment]
got user accounts working (ish) just now. ran into some confusion when the hash made with [this](https://nodejs.org/api/crypto.html#crypto_crypto_pbkdf2_password_salt_iterations_keylen_digest_callback) didn't fit in the database. then I realized the node module passport-local-sequelize instantiated the hash column as a STRING datatype, which has a limited size. I switched the type to TEXT and things are working

**Comment by duncangraham** [comment]
login is now working as well. was scratching my head for a little trying to debug it till i realized the view code was posting to the right place but still had the old 'onclick='toLogin(this.form)' code. removed that and things work great

**Comment by duncangraham** [comment]
the basics are done, merging the accounts branch and closing this. 

next up are refinements to this work. MORE TICKETS COMIN! BRACE YOURSELVES LADS.
