### ISSUE TITLE
implement layouts and partials

### ISSUE THREAD

**Issue by duncangraham** [freindst/Argo-Project-V0#5]
We need to get rid of the duplicate code in the views folder. making a small change currently means rewriting a bunch of files.

@freindst it looks like you aren't using jade now, can I remove it in favor of express-handlebars? (https://www.npmjs.com/package/express3-handlebars)

I'll be working on the layout branch

**Comment by duncangraham** [comment]
based on https://github.com/freindst/Argo-Project-V0/pull/1#issuecomment-121468108 I'm down to start transferring the view code to Jade layouts and partials. Until this happens I'm going to be blocked from moving forward. Do you mind if I tackle this @freindst?

**Comment by freindst** [comment]
Feel free to do it. Jade is just another form of HTML+JavaScript

**Comment by duncangraham** [comment]
Ok cool, I'm decently familiar with jade already. I'll start that work tomorrow

The current blocker is that for the front end changes I'd like to make I would need to change duplicate code spread across the files in the views folder. Since making layouts and partials will help with the front end changes (and changes down the road) its a priority for me

**Comment by freindst** [comment]
In my opinion, I would gradually separate script codes with template in order to fit MVC pattern. I believe your layouts won't affect my back-end work much. So, feel free to do your work. If necessary, I can create script-free version for you in advance if you need.

**Comment by freindst** [comment]
i am not sure what I will start first right now. I have to collect all your ideas tomorrow, in order to build a whole work plan for myself.

**Comment by freindst** [comment]
I found that the file where you changed the port number is app.js. I remember out team was using "createTrip.js". Did you create app.js on your own? If these two .js files are identical, I may delete "createTrip.js" and begin to use "app.js" as node.js entry file in future.

**Comment by duncangraham** [comment]
Made solid progress tonight. got the base of a layout and some partials (like the contents of <head> and the navbar) started. Will push tomorrow to crush as many pages as I can hit so I can move onto adding more features.

cc @markstm17

**Comment by duncangraham** [comment]
this is done. I'll merge with master now
