### ISSUE TITLE
When I click reset, the words and numbers do not disappear

### ISSUE THREAD

**Issue by markstm17** [freindst/Argo-Project-V0#69]
![screen shot 2015-08-02 at 9 48 54 pm](https://cloud.githubusercontent.com/assets/11848699/9030541/9f79d7a8-3969-11e5-8f1c-bbcc170986e0.png)

**Comment by duncangraham** [comment]
I would advocate to remove the reset button completely. I don't think it's necessary. 

If people want to reset the form they can reload the page. same goes with cancel. If people don't want to create a bus, then close the browser window. having three buttons is confusing and unnecessary.

**Comment by duncangraham** [comment]
fixed with [this commit](https://github.com/freindst/Argo-Project-V0/commit/b3015bd5f6eea1ddb7be9e45a5a1a0fb209fa3dc)
